action: ???
name: ???
modality: ???
total_batch: ??? 
batch_size: ???
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 
amp: ???  #automatic mixed precision
profile: ??? # profile the training

train:
  num_iter: ???  #total_batch=128.  6955/128=54.33 ->1 epoch || total_batch=256.  6955/256=27.16 ->1 epoch
  eval_freq: ???  #every 25% of an epoch
  max_grad_norm: ???
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: ??? 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???

models:
  RGB:
    model: ???
    kwargs: {}
    lr: ???
    weight_decay: ???
    dropout: 0.1
  DEPTH:
    model: ???
    kwargs: {}
    lr: ???
    weight_decay: ???
    dropout: 0.1
  FUSION:
    model: ???
    kwargs: {}
    lr: ???
    weight_decay: ???
    dropout: 0.1
