action: ???
name: ???
modality: ???
total_batch: ??? 
batch_size: ???
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 
amp: ???  #automatic mixed precision

train:
  num_iter: ???  #if total_batch of 128.  7793/128=60.88 ->1 epoch
  eval_freq: ???  #every 25% of an epoch
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: 4 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???

models:
  RGB:
    model: ???
    kwargs: {}
    lr: 5e-4
    sgd_momentum: 0.9
    weight_decay: 1e-4
  DEPTH:
    model: ???
    kwargs: {}
    lr: 1e-3
    sgd_momentum: 0.9
    weight_decay: 1e-4
  FUSION:
    model: ???
    kwargs: {}
    lr: 1e-3
    sgd_momentum: 0.9
    weight_decay: 1e-4
