action: ???
name: ???
modality: ???
total_batch: 32 
batch_size: 32 
gpus: null 
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 
fusion_modalities: True

train:
  num_iter: 200 
  lr_steps: 190 
  eval_freq: 10 
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: 4 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???
  MESH:
   data_path: ???

models:
  RGB:
    model: ???
    normalize: ???
    dropout: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  DEPTH:
    model: ???
    normalize: ???
    dropout: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  MESH:
    model: ???
    normalize: ???
    dropout: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
