action: ???
name: ???
modality: ???
total_batch: ??? 
batch_size: ???
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 
amp: ???  #automatic mixed precision
profile: ??? # profile the training

train:
  num_iter: ???  #total_batch=128.  7793/128=60.88 ->1 epoch || total_batch=256.  7793/256=30.44 ->1 epoch
  eval_freq: ???  #every 25% of an epoch
  max_grad_norm: ???
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: ??? 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???

models:
  RGB:
    model: ???
    kwargs: {}
    lr: ???
    sgd_momentum: 0.9
    weight_decay: 1e-4
  DEPTH:
    model: ???
    kwargs: {}
    lr: ???
    sgd_momentum: 0.9
    weight_decay: 1e-4
  FUSION:
    model: ???
    kwargs: {}
    lr: ???
    sgd_momentum: 0.9
    weight_decay: 1e-4
