action: ???
name: ???
modality: ???
total_batch: 128 
batch_size: 32 
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 

train:
  num_iter: 10000 
  eval_freq: 60 
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: 4 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???

models:
  RGB:
    model: ???
    kwargs: {}
    lr: 1e-5
    sgd_momentum: 0.9
    weight_decay: 1e-4
  DEPTH:
    model: ???
    kwargs: {}
    lr: 1e-3
    sgd_momentum: 0.9
    weight_decay: 1e-4
  FUSION:
    model: ???
    kwargs: {}
    lr: 1e-3
    sgd_momentum: 0.9
    weight_decay: 1e-4
