action: ???
name: ???
modality: ???
total_batch: 128 
batch_size: 32 
wandb_name: null 
resume_from: null 
logname: null 
models_dir: null 
fusion_modalities: ???

train:
  num_iter: 10000 
  lr_steps: 2500 
  eval_freq: 100 
  
test:
  
dataset:
  name: ???
  annotations_path: ???
  workers: 4 
  resolution: 224 
  RGB:
    data_path: ???
  DEPTH:
    data_path: ???

models:
  RGB:
    model: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  DEPTH:
    model: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  FUSION:
    model: ???
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
