action: train # train or test
name: training # name of the experiment needed for the logs
modality: ['RGB', 'DEPTH'] #["RGB","DEPTH"] #['VOXEL'] #['MESH']
total_batch: 32
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models
fusion_modalities: True

train:
  num_iter: 5
  lr_steps: 1
  eval_freq: 1
  
test:
  
dataset:
  name: CalD3r_MenD3s #Bosphorus 
  annotations_path: ..\Datasets  
  workers: 4 
  resolution: 224 
  RGB:
    data_path:  ..\Datasets
  DEPTH:
    data_path: ..\Datasets
  MESH:
    data_path: ..\Datasets

models:
  RGB:
    model: RGB_ResNet18
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  DEPTH:
    model: DEPTH_ResNet18
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  FUSION:
    model: att_sel_fusion #feat_fusion #att_sel_dusion #ViT
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
