action: train # train or test
name: training # name of the experiment needed for the logs
modality: ['RGB', 'DEPTH'] #["RGB","DEPTH"] #['VOXEL'] #['MESH']
total_batch: 32
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models

train:
  num_iter: 200 #10000?? number of training iterations with BATCH_SIZE (32) NOT on TOTAL_BATCH (128)
  lr_steps: 180 #8500 steps before reducing learning rate
  eval_freq: 5 # evaluation frequency
  
test:
  
dataset:
  name: CalD3r_MenD3s #Bosphorus 
  annotations_path: ..\Datasets  #train_val  #Action-Net/data/ #!!!!
  workers: 4 # number of workers for the dataloader
  resolution: 224 # input resolution to the model
  RGB:
    data_path:  ..\Datasets
  DEPTH:
    data_path: ..\Datasets
  MESH:
    data_path: ..\Datasets

# these are the action recognition models for each modality
models:
  RGB:
    model: RGB_CNN
    normalize: False
    dropout: 0.4
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  DEPTH:
    model: DEPTH_CNN
    normalize: False
    dropout: 0.5
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  MESH:
    model: MESH_CNN
    normalize: False
    dropout: 0.5
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
