action: train # train or test
name: training # name of the experiment needed for the logs
modality: ['RGB', 'DEPTH'] #["RGB","DEPTH"] #['VOXEL'] #['MESH']
total_batch: 128
batch_size: 32 # batch size for the forward
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models
fusion_modalities: True

train:
  num_iter: 10000
  lr_steps: 1000 #use cosine-annealing instead
  eval_freq: 100
  
test:
  
dataset:
  name: CalD3r_MenD3s #Bosphorus 
  annotations_path: ..\Datasets #..\Datasets  
  workers: 4 
  resolution: 224 
  RGB:
    data_path:  ..\Datasets #..\Datasets  
  DEPTH:
    data_path: ..\Datasets #..\Datasets  

models:
  RGB:
    model: ViT
    kwargs: {}
    lr_steps: 3000
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7
  DEPTH:
    model: DEPTH_ResNet18
    kwargs: {}
    lr_steps: 3000
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7
  FUSION:
    model: att_fusion1D #feat_fusion #att_fusion1D #att_sel_fusion #ViT
    kwargs: {}
    lr_steps: 3000
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7
